<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем функцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.83236779 0.75099561 0.13276983 ... 0.14716833 0.11780403 0.73849687]
 [0.01272938 0.80232368 0.2495481  ... 0.32141947 0.58544143 0.26039159]
 [0.30363074 0.55273736 0.09416044 ... 0.98305596 0.38348352 0.86861769]
 ...
 [0.46313789 0.6230086  0.42120659 ... 0.26128825 0.19294066 0.20797616]
 [0.20826783 0.51155091 0.41214477 ... 0.49829017 0.25548037 0.37879374]
 [0.05561464 0.93718071 0.33327175 ... 0.86645238 0.78019803 0.78010182]]
[[0.25168928 0.38584539 0.02380001 ... 0.82068473 0.9270351  0.20143607]
 [0.44992355 0.95342536 0.80163891 ... 0.98004783 0.14711787 0.40272604]
 [0.5955726  0.67520943 0.73115625 ... 0.35089824 0.63744406 0.32589198]
 ...
 [0.88781212 0.04590216 0.64202394 ... 0.73005818 0.56150045 0.74368792]
 [0.70548051 0.88597174 0.34591063 ... 0.2091051  0.68584791 0.09295419]
 [0.45478834 0.43657915 0.80141404 ... 0.14146779 0.89876262 0.99523902]]


In [10]:
def mult(first, second):
    """
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b

    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    result = []
    for i in range(len(first)):
        result_row = []
        for j in range(len(second[0])):
            result_ij = sum(first[i][k] * second[k][j] for k in range(len(first)))
            result_row.append(result_ij)
        result.append(result_row)
    
    result = np.array(result)
    
    return result

In [4]:
def numpy_mult(first, second):
    """
    first: np.array[size, size]             --- первая матрица-аргумент
    second: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b

    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    return first.dot(second)

In [11]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 223 ms, sys: 1.62 ms, total: 224 ms
Wall time: 224 ms


In [12]:
M1

array([[25.53951091, 23.65898617, 27.53017922, ..., 23.29623872,
        27.54799919, 24.46206405],
       [24.43441897, 24.01687798, 26.27534641, ..., 21.81722437,
        26.42997678, 24.51158567],
       [25.3809718 , 23.51538122, 27.58111289, ..., 24.94213533,
        26.69490055, 25.0806468 ],
       ...,
       [22.78385263, 24.69027372, 26.1988131 , ..., 23.37045776,
        25.69210423, 25.2264285 ],
       [22.68567821, 23.21456531, 25.21103744, ..., 23.02528937,
        25.55607582, 24.96880284],
       [25.59261123, 25.4228372 , 27.50149746, ..., 23.2494329 ,
        26.71768442, 24.64162706]])

In [7]:
%%time
# засечем время работы функции с NumPy
M2 = numpy_mult(a, b)

CPU times: user 1.33 ms, sys: 0 ns, total: 1.33 ms
Wall time: 164 µs


In [8]:
M2

array([[25.53951091, 23.65898617, 27.53017922, ..., 23.29623872,
        27.54799919, 24.46206405],
       [24.43441897, 24.01687798, 26.27534641, ..., 21.81722437,
        26.42997678, 24.51158567],
       [25.3809718 , 23.51538122, 27.58111289, ..., 24.94213533,
        26.69490055, 25.0806468 ],
       ...,
       [22.78385263, 24.69027372, 26.1988131 , ..., 23.37045776,
        25.69210423, 25.2264285 ],
       [22.68567821, 23.21456531, 25.21103744, ..., 23.02528937,
        25.55607582, 24.96880284],
       [25.59261123, 25.4228372 , 27.50149746, ..., 23.2494329 ,
        26.71768442, 24.64162706]])

In [13]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

In [14]:
223 / 1.33

167.6691729323308

Функции выдали идентичный корректный результат.

Добавил в функцию mult

```
# преобразование результата функции в массив numpy
# чтобы проверить идентичность массивов
result = np.array(result)
```

Вариант с использованием numpy отработал в 167 раз быстрее.

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [15]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.35113962 0.1753663  0.44653565] [0.2350411  0.24903142 0.27347221]


In [17]:
def no_numpy_scalar(v1, v2):
    """
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """
    if len(v1) == len(v2):
        return sum(x*y for x, y in zip(v1, v2))

In [18]:
def numpy_scalar(v1, v2):
    """
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """
    if len(v1) == len(v2):
        return v1.dot(v2)

In [19]:
%time product_1 = no_numpy_scalar(a,b)
%time product_2 = numpy_scalar(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: user 8 µs, sys: 5 µs, total: 13 µs
Wall time: 14.8 µs
CPU times: user 8 µs, sys: 5 µs, total: 13 µs
Wall time: 14.5 µs


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [20]:
def np_diag_2k(a):
    """
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    diag = np.diag(a)

    return sum(diag[diag % 2 == 0])

In [21]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[2, 1, 9, 6, 3],
       [1, 3, 2, 2, 1],
       [5, 3, 2, 4, 8],
       [1, 8, 1, 2, 5],
       [3, 6, 7, 4, 6]])

In [22]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 28 µs, sys: 15 µs, total: 43 µs
Wall time: 44.1 µs


12

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​

In [23]:
def cumsum(A):
    """
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    result = []
    for row in A:
        row = np.array(row)
        result.append(row.cumsum())
        
    return result

In [24]:
# зададим некоторую последовательность и проверим ее на вашей функции.
A = sps.uniform.rvs(size=10**3)

%time S2 = cumsum(A)

CPU times: user 2.15 ms, sys: 0 ns, total: 2.15 ms
Wall time: 2.15 ms


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [25]:
from copy import copy
def transform(X, a=1):
    """
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке,
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    result = []
    for row in X:
        reference = np.array(row)
        row = np.array(row)
        row[1::2] = a
        row[::2] = row[::2]**3
        row = row[::-1]
        result.append(np.hstack((reference, row)))
    result = np.array(result)
    
    return result

In [27]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = transform(X, 5)

CPU times: user 134 µs, sys: 0 ns, total: 134 µs
Wall time: 191 µs


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [28]:
def run_length_encoding(arr):
    """
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор
    repetitions добавляет длины последовательностей подряд идущих повторений.
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    # вычисляем разницу между последующими элементами
    diff = np.diff(arr)
    print(diff)

    # находим индексы, где разница не равна 0
    idx = np.where(diff != 0)[0]
    print(idx)

    # прибавляем 1, т.к. основная индексация начинается с 0, и к концу добавляем общую длину массива
    idx = np.r_[idx, arr.size - 1]
    print(idx)

    # находим элементы
    elements = arr[idx]

    # находим количество повторений, учитывая, что numpy разчитывает индексы от 0
    counts = np.diff(np.r_[-1, idx])

    return (elements, counts)

In [30]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = run_length_encoding(X)

[ 1  0  1  0 -2  0  4  0 -3  1  0]
[0 2 4 6 8 9]
[ 0  2  4  6  8  9 11]
CPU times: user 933 µs, sys: 0 ns, total: 933 µs
Wall time: 850 µs
