In [4]:
import numpy as np

def cumsum(A):
    result = []
    for row in A:
        row = np.array(row)
        result.append(row.cumsum())
    return result


In [5]:
mtx = [
    [1, 2, 34],
    [12, 14, 5],
    [1, 65, 34]
]

In [6]:
print(np.array(cumsum(mtx)))

[[  1   3  37]
 [ 12  26  31]
 [  1  66 100]]
