In [8]:
import numpy as np

def no_numpy_mult(first, second):
    result = []
    for i in range(len(first)):
        result_row = []
        for j in range(len(second[0])):
            result_ij = sum(first[i][k] * second[k][j] for k in range(len(first)))
            result_row.append(result_ij)
        result.append(result_row)
    
    return result

def numpy_mult(first, second):
    return first.dot(second)

In [9]:
mtx1 = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
]

mtx2 = [
    [12, 3, 4],
    [5, 6, 7],
    [23, 1, -1]
]

In [13]:
print(no_numpy_mult(mtx1, mtx2))

[[12, 3, 4], [5, 6, 7], [23, 1, -1]]


In [11]:
mtx1 = np.array(mtx1)
mtx2 = np.array(mtx2)

In [12]:
print(numpy_mult(mtx1, mtx2))

[[12  3  4]
 [ 5  6  7]
 [23  1 -1]]
