In [1]:
import numpy as np

def run_length_encoding(arr):
    # вычисляем разницу между последующими элементами
    diff = np.diff(arr)
    print(diff)

    # находим индексы, где разница не равна 0
    idx = np.where(diff != 0)[0]
    print(idx)

    # прибавляем 1, т.к. основная индексация начинается с 0, и к концу добавляем общую длину массива
    idx = np.r_[idx, arr.size - 1]
    print(idx)

    # находим элементы
    elements = arr[idx]

    # находим количество повторений, учитывая, что numpy разчитывает индексы от 0
    counts = np.diff(np.r_[-1, idx])

    return (elements, counts)

In [2]:
arr = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
elements, counts = run_length_encoding(arr)

[ 1  0  1  0 -2  0  4  0 -3  1  0]
[0 2 4 6 8 9]
[ 0  2  4  6  8  9 11]


In [3]:
print('Elements:', elements)
print('Counts:', counts)

Elements: [1 2 3 1 5 2 3]
Counts: [1 2 2 2 2 1 2]
